global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "victoriametrics"
    static_configs:
      - targets: ["victoriametrics:8428"]

  - job_name: "nodeexporter"
    static_configs:
      - targets: ["nodeexporter:9100"]
    # - targets: ["host.docker.internal:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "app"
    static_configs:
      - targets: ["app:8081/metrics"]
      - targets: ["app:8082/metrics"]